### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by st-schneider** [Raathigesh/waypoint#19] opened 2020-07-30 06:52 UTC
Issue Type: <b>Bug</b>

When I close the waypoint webview and reopen it I get a connection refused and the webview stays empty.

<img width="777" alt="grafik" src="https://user-images.githubusercontent.com/30625381/88890484-fac2d080-d241-11ea-85bb-080b8077f08f.png">

Extension version: 0.38.4
VS Code version: Code - Insiders 1.48.0-insider (15e798e081984a17eae00de91adf4479190d5ed2, 2020-07-28T10:40:03.139Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 13, 8|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 3b7acc73-7f05-4994-b539-24b72f428fcd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Raathigesh** [comment] 2020-08-03 10:44
Closing this since the other issue you created also seems to be the same root cause. Will investigate the other one.

**Closed as completed by Raathigesh** 2020-08-03 10:44 UTC
